jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: setup repository
        uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm install
      - run: npm run lint
    timeout-minutes: 10
name: Lint
on:
  push:
    branches:
      - main
